name: Build Common

on:
  push:
    paths:
      - 'package.json'
      - '.github/workflows/build.yml'

jobs:
  publish-npm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          registry-url: https://registry.npmjs.org/
      - run: corepack enable

      - shell: bash
        name: Log yarn version
        run: yarn -v

      - name: Install
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
